#!/usr/bin/env python
"""
Compare Standard (Single-Stage) vs. Two-Stage NXRO Models.

This script reads the ranking CSVs generated by rank_all_variants_out_of_sample.py
and generates comparative plots and tables.

Usage:
    python compare_single_vs_two_stage.py
"""

import os
import argparse
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

def ensure_dir(path):
    os.makedirs(path, exist_ok=True)

def load_data(single_stage_path, two_stage_path):
    if not os.path.exists(single_stage_path):
        raise FileNotFoundError(f"Single-stage results not found at: {single_stage_path}")
    if not os.path.exists(two_stage_path):
        raise FileNotFoundError(f"Two-stage results not found at: {two_stage_path}")
        
    df_single = pd.read_csv(single_stage_path)
    df_two = pd.read_csv(two_stage_path)
    
    return df_single, df_two

def apply_display_names(df):
    """Apply consistent display names to model names."""
    # Mapping from CSV model names to display names
    name_mapping = {
        'Res': 'NXRO+MLP Residual',
        'Graph Fixed Xro': 'NXRO + Graph Residual',
        'Attentive': 'NXRO+Attention Residual',
        'Neural': 'Neural ODE',
        'Transformer': 'Transformer',
        'XRO': 'XRO (baseline)',
        'Linear': 'NXRO-Linear',
        'Neural Phys': 'Neural ODE (Physics)',
        'RO+Diag': 'RO+Diag',
        'RO+Diag FixNL': 'RO+Diag FixNL',
        'RO+Diag FixRO': 'RO+Diag FixRO',
        'ResidualMix FixRO': 'ResidualMix FixRO',
        'Graphpyg Gat K3': 'GraphPyG GAT K3',
    }
    
    df = df.copy()
    
    def map_name(name):
        # Remove (Two-Stage) suffix for matching
        base_name = name.replace(' (Two-Stage)', '')
        if base_name in name_mapping:
            mapped = name_mapping[base_name]
            # Re-add suffix if it was present
            if '(Two-Stage)' in name:
                return mapped + ' (Two-Stage)'
            return mapped
        return name
    
    df['Display_Name'] = df['Model'].apply(map_name)
    return df


def filter_pathological_cases(df):
    """Filter out models with inf or NaN RMSE/ACC values."""
    df = df.copy()
    # Filter out rows with inf or NaN in key metrics
    mask = (
        np.isfinite(df['Mean_RMSE_Test']) & 
        np.isfinite(df['Mean_ACC_Test']) &
        np.isfinite(df['Mean_RMSE_Train']) & 
        np.isfinite(df['Mean_ACC_Train'])
    )
    filtered = df[mask]
    n_removed = len(df) - len(filtered)
    if n_removed > 0:
        removed_models = df[~mask]['Model'].tolist()
        print(f"  Filtered out {n_removed} pathological model(s): {removed_models}")
    return filtered


def match_models(df_single, df_two):
    """Match models between single and two-stage dataframes."""
    # Filter out pathological cases first
    df_single = filter_pathological_cases(df_single)
    df_two = filter_pathological_cases(df_two)
    
    # Apply display names first
    df_single = apply_display_names(df_single)
    df_two = apply_display_names(df_two)
    
    # Create a matching key for two-stage models by stripping the suffix
    # e.g., "NXRO+MLP Residual (Two-Stage)" -> "NXRO+MLP Residual"
    df_two = df_two.copy()
    df_two['Match_Name'] = df_two['Display_Name'].str.replace(' (Two-Stage)', '', regex=False)
    
    # Clean single stage names if needed (though they should be clean)
    df_single = df_single.copy()
    df_single['Match_Name'] = df_single['Display_Name']
    
    # Merge
    # Use inner join to compare only models present in both
    merged = pd.merge(
        df_single, 
        df_two, 
        on='Match_Name', 
        suffixes=('_Single', '_TwoStage'),
        how='inner'
    )
    
    return merged

def plot_comparison(merged_df, metric, output_dir):
    """Generate bar plot comparing single vs two-stage for a given metric."""
    df = merged_df.sort_values(f'Mean_{metric}_Test_Single')
    
    n_models = len(df)
    fig, ax = plt.subplots(figsize=(max(10, 0.5 * n_models), 8))
    
    x = np.arange(n_models)
    width = 0.35
    
    col_single = f'Mean_{metric}_Test_Single'
    col_two = f'Mean_{metric}_Test_TwoStage'
    
    # Determine better/worse colors
    # For RMSE, lower is better. For ACC, higher is better.
    if metric == 'RMSE':
        is_better = df[col_two] < df[col_single]
    else:
        is_better = df[col_two] > df[col_single]
        
    rects1 = ax.bar(x - width/2, df[col_single], width, label='Single-Stage (Train ORAS5)', color='gray', alpha=0.6)
    
    # Color two-stage bars based on improvement
    colors = ['tab:green' if b else 'tab:red' for b in is_better]
    rects2 = ax.bar(x + width/2, df[col_two], width, label='Two-Stage (Synth -> ORAS5)', color=colors, alpha=0.8)
    
    ax.set_xlabel('Model')
    ax.set_ylabel(f'Test {metric}' + (' (°C)' if metric == 'RMSE' else ''))
    ax.set_title(f'{metric}: Single-Stage vs Two-Stage Training (Out-of-Sample)', fontsize=14)
    ax.set_xticks(x)
    ax.set_xticklabels(df['Match_Name'], rotation=45, ha='right')
    
    # Custom legend
    from matplotlib.lines import Line2D
    custom_lines = [
        Line2D([0], [0], color='gray', lw=4, alpha=0.6),
        Line2D([0], [0], color='tab:green', lw=4, alpha=0.8),
        Line2D([0], [0], color='tab:red', lw=4, alpha=0.8)
    ]
    ax.legend(custom_lines, ['Single-Stage', 'Two-Stage (Improved)', 'Two-Stage (Worse)'])
    
    ax.grid(True, axis='y', alpha=0.3)
    plt.tight_layout()
    
    out_path = f'{output_dir}/comparison_single_vs_two_stage_{metric.lower()}.png'
    plt.savefig(out_path, dpi=300)
    plt.close()
    print(f"  ✓ Saved plot: {out_path}")

def plot_overall_ranking(df_single, df_two, output_dir):
    """Plot overall ranking of top 5 models + XRO (mixed single and two-stage)."""
    
    # Filter out pathological cases first
    df_single = filter_pathological_cases(df_single)
    df_two = filter_pathological_cases(df_two)
    
    # Apply display names
    df_single = apply_display_names(df_single)
    df_two = apply_display_names(df_two)
    
    # 1. Prepare combined dataframe
    cols = ['Display_Name', 'Mean_ACC_Test', 'Mean_RMSE_Test']
    
    # Ensure columns exist
    for df in [df_single, df_two]:
        for col in cols:
            if col not in df.columns:
                print(f"Warning: Column {col} not found. Skipping overall ranking plot.")
                return

    df_combined = pd.concat([df_single[cols].rename(columns={'Display_Name': 'Model'}), 
                            df_two[cols].rename(columns={'Display_Name': 'Model'})], ignore_index=True)
    
    # 2. Add XRO Baseline (if not already in data)
    # Values from results_out_of_sample.md or known baseline
    if 'XRO (baseline)' not in df_combined['Model'].values:
        xro_row = pd.DataFrame([{
            'Model': 'XRO (baseline)',
            'Mean_ACC_Test': 0.596,
            'Mean_RMSE_Test': 0.605
        }])
        df_combined = pd.concat([df_combined, xro_row], ignore_index=True)
    
    # 3. Generate plots for RMSE and ACC
    for metric in ['RMSE', 'ACC']:
        col_name = f'Mean_{metric}_Test'
        
        # Sort
        if metric == 'RMSE':
            # Lower is better
            df_sorted = df_combined.sort_values(col_name, ascending=True)
        else:
            # Higher is better
            df_sorted = df_combined.sort_values(col_name, ascending=False)
            
        # Get top 5 models
        top_5 = df_sorted.head(5).copy()
        
        # Check if XRO is in top 5
        xro_in_top5 = 'XRO (baseline)' in top_5['Model'].values
        
        # If XRO not in top 5, append it for comparison
        if not xro_in_top5:
            xro_entry = df_combined[df_combined['Model'] == 'XRO (baseline)']
            plot_df = pd.concat([top_5, xro_entry], ignore_index=True)
        else:
            plot_df = top_5
            
        # Plot
        plt.figure(figsize=(10, 6))
        
        # Colors: Highlight XRO, distinguish others
        colors = []
        for model in plot_df['Model']:
            if 'XRO (baseline)' in model:
                colors.append('black')
            elif '(Two-Stage)' in model:
                colors.append('tab:green') # Two-stage
            else:
                colors.append('tab:blue') # Single-stage
                
        bars = plt.bar(plot_df['Model'], plot_df[col_name], color=colors, alpha=0.7)
        
        # Add values on top
        for bar in bars:
            height = bar.get_height()
            plt.text(bar.get_x() + bar.get_width()/2., height,
                    f'{height:.3f}',
                    ha='center', va='bottom', fontsize=9)
            
        plt.title(f'Top Models vs XRO Baseline ({metric})', fontsize=14)
        plt.ylabel(f'Test {metric}' + (' (°C)' if metric == 'RMSE' else ''))
        plt.xticks(rotation=45, ha='right')
        plt.grid(True, axis='y', alpha=0.3)
        
        # Legend
        from matplotlib.patches import Patch
        legend_elements = [
            Patch(facecolor='tab:blue', alpha=0.7, label='Single-Stage'),
            Patch(facecolor='tab:green', alpha=0.7, label='Two-Stage'),
            Patch(facecolor='black', alpha=0.7, label='XRO (baseline)')
        ]
        plt.legend(handles=legend_elements)
        
        plt.tight_layout()
        out_path = f'{output_dir}/overall_ranking_top5_vs_xro_{metric.lower()}.png'
        plt.savefig(out_path, dpi=300)
        plt.close()
        print(f"  ✓ Saved overall ranking plot: {out_path}")

def main():
    parser = argparse.ArgumentParser(description='Compare Single vs Two-Stage NXRO Models')
    parser.add_argument('--metric', type=str, default='combined', help='Metric suffix used in filenames (e.g., combined, rmse)')
    parser.add_argument('--results_dir', type=str, default='results_out_of_sample/rankings')
    parser.add_argument('--remove_wwv', action='store_true', help='Compare no-WWV experiment results')
    args = parser.parse_args()
    
    # Handle no-WWV configuration
    if args.remove_wwv:
        # If results_dir wasn't explicitly set, use the no-WWV default
        if args.results_dir == 'results_out_of_sample/rankings':
            args.results_dir = 'results_out_of_sample_no_wwv/rankings'
        wwv_suffix = '_no_wwv'
    else:
        wwv_suffix = ''
    
    single_path = f'{args.results_dir}/all_variants_ranked_{args.metric}_out_of_sample{wwv_suffix}.csv'
    two_stage_path = f'{args.results_dir}/all_variants_ranked_{args.metric}_out_of_sample_two_stage{wwv_suffix}.csv'
    
    print("="*80)
    print("COMPARING SINGLE-STAGE VS TWO-STAGE MODELS")
    print("="*80)
    print(f"Single-stage file: {single_path}")
    print(f"Two-stage file:    {two_stage_path}")
    print()
    
    try:
        df_single, df_two = load_data(single_path, two_stage_path)
    except FileNotFoundError as e:
        print(f"Error: {e}")
        print("Please ensure both rankings have been generated.")
        return

    merged = match_models(df_single, df_two)
    
    if len(merged) == 0:
        print("Error: No matching models found between the two files.")
        return
        
    print(f"Found {len(merged)} matching models.")
    print()
    
    # Calculate deltas
    merged['Delta_RMSE'] = merged['Mean_RMSE_Test_TwoStage'] - merged['Mean_RMSE_Test_Single']
    merged['Delta_ACC'] = merged['Mean_ACC_Test_TwoStage'] - merged['Mean_ACC_Test_Single']
    
    # Sort by RMSE improvement (negative delta is better)
    summary = merged[[
        'Match_Name', 
        'Mean_RMSE_Test_Single', 'Mean_RMSE_Test_TwoStage', 'Delta_RMSE',
        'Mean_ACC_Test_Single', 'Mean_ACC_Test_TwoStage', 'Delta_ACC'
    ]].sort_values('Delta_RMSE')
    
    print("COMPARISON SUMMARY (Sorted by RMSE Improvement):")
    print("-" * 100)
    # Format for nice printing
    pd.options.display.float_format = '{:.4f}'.format
    print(summary.to_string(index=False))
    print("-" * 100)
    print("Note: Negative Delta_RMSE means Two-Stage is BETTER.")
    print("      Positive Delta_ACC  means Two-Stage is BETTER.")
    print()
    
    # Save summary CSV
    out_csv = f'{args.results_dir}/comparison_single_vs_two_stage_summary.csv'
    summary.to_csv(out_csv, index=False)
    print(f"✓ Saved summary CSV to: {out_csv}")
    
    # Generate Plots
    plot_comparison(merged, 'RMSE', args.results_dir)
    plot_comparison(merged, 'ACC', args.results_dir)
    
    # Generate Overall Ranking Plot (Top 5 + XRO)
    plot_overall_ranking(df_single, df_two, args.results_dir)
    
    # Overall stats
    better_rmse = (merged['Delta_RMSE'] < 0).sum()
    better_acc = (merged['Delta_ACC'] > 0).sum()
    print()
    print(f"Summary Stats:")
    print(f"  Models improved in RMSE: {better_rmse}/{len(merged)} ({better_rmse/len(merged)*100:.1f}%)")
    print(f"  Models improved in ACC:  {better_acc}/{len(merged)} ({better_acc/len(merged)*100:.1f}%)")
    print(f"  Avg RMSE Change: {merged['Delta_RMSE'].mean():.4f} °C")
    print(f"  Avg ACC Change:  {merged['Delta_ACC'].mean():.4f}")
    print("="*80)

if __name__ == '__main__':
    main()

